"""LLM Prompts for all agents."""

from .security_prompts import (
    SECURITY_ANALYSIS_PROMPT,
    SECURITY_CONTEXT_PROMPT,
    AUTH_ANALYSIS_PROMPT,
    INPUT_VALIDATION_PROMPT,
    CRYPTO_ANALYSIS_PROMPT,
)

from .performance_prompts import (
    PERFORMANCE_ANALYSIS_PROMPT,
    SCALABILITY_PREDICTION_PROMPT,
    MEMORY_ANALYSIS_PROMPT,
)

from .functional_prompts import (
    FUNCTIONAL_ANALYSIS_PROMPT,
    EDGE_CASE_ANALYSIS_PROMPT,
    TEST_QUALITY_PROMPT,
)

from .logic_prompts import (
    LOGIC_ANALYSIS_PROMPT,
    RACE_CONDITION_PROMPT,
    STATE_MACHINE_PROMPT,
)

from .architecture_prompts import (
    ARCHITECTURE_ANALYSIS_PROMPT,
    CLEAN_ARCHITECTURE_PROMPT,
    MICROSERVICE_BOUNDARY_PROMPT,
)

from .technical_debt_prompts import TECHNICAL_DEBT_PROMPT, REFACTORING_SUGGESTION_PROMPT

from .observability_prompts import (
    OBSERVABILITY_PROMPT,
    LOGGING_IMPROVEMENT_PROMPT,
    METRICS_SUGGESTION_PROMPT,
)

from .resilience_prompts import (
    RESILIENCE_PROMPT,
    CIRCUIT_BREAKER_PROMPT,
    RETRY_PATTERN_PROMPT,
)

from .semantics_prompts import (
    SEMANTICS_PROMPT,
    NAMING_IMPROVEMENT_PROMPT,
    CODE_EXPLANATION_PROMPT,
)

from .deployment_prompts import (
    DEPLOYMENT_PROMPT,
    MIGRATION_SAFETY_PROMPT,
    FEATURE_FLAG_PROMPT,
)

__all__ = [
    # Security
    "SECURITY_ANALYSIS_PROMPT",
    "SECURITY_CONTEXT_PROMPT",
    "AUTH_ANALYSIS_PROMPT",
    "INPUT_VALIDATION_PROMPT",
    "CRYPTO_ANALYSIS_PROMPT",
    # Performance
    "PERFORMANCE_ANALYSIS_PROMPT",
    "SCALABILITY_PREDICTION_PROMPT",
    "MEMORY_ANALYSIS_PROMPT",
    # Functional
    "FUNCTIONAL_ANALYSIS_PROMPT",
    "EDGE_CASE_ANALYSIS_PROMPT",
    "TEST_QUALITY_PROMPT",
    # Logic
    "LOGIC_ANALYSIS_PROMPT",
    "RACE_CONDITION_PROMPT",
    "STATE_MACHINE_PROMPT",
    # Architecture
    "ARCHITECTURE_ANALYSIS_PROMPT",
    "CLEAN_ARCHITECTURE_PROMPT",
    "MICROSERVICE_BOUNDARY_PROMPT",
    # Technical Debt
    "TECHNICAL_DEBT_PROMPT",
    "REFACTORING_SUGGESTION_PROMPT",
    # Observability
    "OBSERVABILITY_PROMPT",
    "LOGGING_IMPROVEMENT_PROMPT",
    "METRICS_SUGGESTION_PROMPT",
    # Resilience
    "RESILIENCE_PROMPT",
    "CIRCUIT_BREAKER_PROMPT",
    "RETRY_PATTERN_PROMPT",
    # Semantics
    "SEMANTICS_PROMPT",
    "NAMING_IMPROVEMENT_PROMPT",
    "CODE_EXPLANATION_PROMPT",
    # Deployment
    "DEPLOYMENT_PROMPT",
    "MIGRATION_SAFETY_PROMPT",
    "FEATURE_FLAG_PROMPT",
]
